Fix image build error when assembly has a basis event (#500)
Fixs

```
  File "/mnt/workspace/jenkins/working/aos-cd-builds/build%2Fcustom/art-tools/doozer/doozerlib/cli/__main__.py", line 557, in dgr_rebase
    (real_version, real_release) = dgr.rebase_dir(version, release, terminate_event, force_yum_updates)
  File "/mnt/workspace/jenkins/working/aos-cd-builds/build%2Fcustom/art-tools/doozer/doozerlib/distgit.py", line 2402, in rebase_dir
    real_version, real_release = self.update_distgit_dir(version, release, prev_release, force_yum_updates)
  File "/mnt/workspace/jenkins/working/aos-cd-builds/build%2Fcustom/art-tools/doozer/doozerlib/distgit.py", line 1582, in update_distgit_dir
    parent_build_nvr = parse_nvr(parent_build_info._nvr)
  File "/home/jenkins/.local/lib/python3.6/site-packages/kobo/rpmlib.py", line 194, in parse_nvr
    nvr_parts = nvr.rsplit("-", 2)
TypeError: 'MissingModel' object is not callable
2021-08-24 04:13:43,922 ERROR [containers/openshift-kubernetes-nmstate-operator] 'MissingModel' object is not callable
```

The field name is `nvr` instead of `_nvr`.